import itertools
import random

import opentamp


GOAL = "(RobotAt spot robot_end_pose)"
HEIGHT = 5
WIDTH = 5
NUM_END = 20


def main():
    for NUM_CANS in range(1, 10):
        filename = "/spot_probs/spot_prob_{0}.prob".format(NUM_CANS)
        s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for NAMO problem instance. Blank lines and lines beginning with # are filtered out.\n\n"
        coords = list(itertools.product(list(range(-HEIGHT, HEIGHT)), list(range(-WIDTH, WIDTH))))
        random.shuffle(coords)

        s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
        s += "Objects: "
        for n in range(NUM_CANS):
            s += "Target (name can%d_init_target); "%(n)
            s += "Can (name can%d); "%(n)
            s += "Target (name can%d_end_target); "%(n)

        s += "Robot (name %s); "%"spot"
        s += "RobotPose (name %s); "%"robot_init_pose"
        s += "RobotPose (name robot_end_pose) \n\n"

        s += "Init: "
        for i in range(NUM_CANS):
            s += "(geom can%d_init_target 0.3), (value can%d_init_target %s), "%(i, i, list(coords[i]))
            s += "(geom can%d 0.3), (pose can%d %s), "%(i, i, list(coords[i]))
            s += "(geom can%d_end_target 0.3), (value can%d_end_target %s), "%(i, i, list(coords[i]))

        s += "(geom %s), (pose %s %s), "%("spot", "spot", [0, 0])
        s += "(theta x [0.]), "
        s += "(theta y [0.]), "
        s += "(theta spot [0.]), "
        s += "(value %s %s), "%("robot_init_pose", [0., 0.])
        s += "(x %s %s), "%("robot_init_pose", [0.])
        s += "(y %s %s), "%("robot_init_pose", [0.])
        s += "(theta %s %s), "%("robot_init_pose", [0.])
        s += "(value %s %s), "%("robot_end_pose", "undefined")
        s += "(x %s %s), "%("robot_end_pose", "undefined")
        s += "(y %s %s), "%("robot_end_pose", "undefined")
        s += "(theta %s %s), "%("robot_end_pose", "undefined")
        s += "(geom %s %s), "%("robot_init_pose", 0.3)
        s += "(geom %s %s), "%("robot_end_pose", 0.3)
        s += "(pose %s [-3.5, 0]), "%"obs0"
        s += "(geom %s %s); "%("obs0", "closet")

        for i in range(NUM_CANS):
            s += "(At can{} can{}_init_target), ".format(i, i)
            s += "(AtInit can{} can{}_init_target), ".format(i, i)
            s += "(AtInit can{} can{}_end_target), ".format(i, i)
            s += "(Near can{} can{}_init_target), ".format(i, i)
        s += "(RobotAt pr2 robot_init_pose), "
        s += "(IsMP pr2), "
        s += "(StationaryW obs0) \n\n"

        s += "Goal: %s"%GOAL

        s += "Invariants: "
        s += "(StationaryBase spot), "
        s += "\n\n"
        
        with open(opentamp.__path__._path[0]+filename, "w") as f:
            f.write(s)

if __name__ == "__main__":
    main()

